### ISSUE TITLE
how do you inject a request to the server api class?

### ISSUE THREAD

**Issue by campin11** [marcgrue/play-scalajs-autowire#2]
I have a hard time figuring this out.

**Comment by marcgrue** [comment]
Yeah, it's a bit convoluted. I might misunderstand your question, but I'll give an answer a go:

There's no server api. The server (`FooServer`) implements the _shared api_ (`FooApi`):

![image](https://user-images.githubusercontent.com/870960/85880559-80cf9f80-b7dc-11ea-9372-8051ab20525b.png)

The server implementation is injected into the FooController:

![image](https://user-images.githubusercontent.com/870960/85881093-62b66f00-b7dd-11ea-8337-99c98437bd8f.png)

Note how the `val` `autowireRouter` is assigned the available routes that you can later call from the client side. The `route` method is an autowire macro that takes the shared interface `FooApi` and its implementation `api` (that we just injected) to implement the possible routes we can access from the client side. This is were the magic happens. It basically implements the shared api on the client side!

This make it possible then to call the methods like `incr` of the shared api from the client side:

![image](https://user-images.githubusercontent.com/870960/85881365-c8a2f680-b7dd-11ea-800c-5f33451a6069.png)

![image](https://user-images.githubusercontent.com/870960/85881401-d3f62200-b7dd-11ea-98af-3ec2062e64ed.png)

The idea is that by setting up this machinery you can focus on simply 3 things:

- the shared api
- server implementations of the shared api
- client calls to the shared api

Hope that was a bit helpful. Let me know if you have more questions or I misunderstood your question...

**Comment by campin11** [comment]
Hi marcgrue, great combination btw, I probably will use this in any of my future development stacks, and thanks for explaining the flows.

sorry for not explaining my question in more details, actually I was having trouble injecting a request 
![image](https://user-images.githubusercontent.com/21018281/85911084-3e967480-b855-11ea-986b-8431f3fbe79d.png)

to the API functions (FooServer)

so I end-up updating the "args" map value in AutowireController to use a value from the session cookie.
I tried with implicit but seems like autowire doesn't support it, so just wondering if you've ever encounter a situation like me before. 

thnaks marcgrue great stuff!

**Comment by marcgrue** [comment]
Glad that you like the setup :-) I'm using it in a [big project](https://github.com/scalamolecule/molecule-admin) and it runs very smoothly!

Unfortunately I don't have much experience with injection since I have worked locally/solo most of the time and haven't had the need for doing authentication for instance. But eventually I'll need it for sure, so I'm very interested in how to get this going in a cool way.

Adding args as you did might not be the solution since they won't reach the server. Only args of the called method defined in the shared api will be passed - the autowire macro pairs only the defined arg names with their arguments. And you might even unintentionally overwrite a key-value pair of the map if some arg of a called method is named "username" or "role"!

Hmm, a hard-coded alternative is to add "username" and "role" as args to the methods defined in the shared api and send empty values from the client and then set (overwrite) them to the session values as you do in `autowireAjax`. Maybe that's the way to go to have authentication on a method-level, although it seems a bit clumsy to have to add "username" and "role" args to every method. At least it would make sure that you receive the username and role data to the server side. Could that be an option?

Can you point to some example of how this is normally done by injecting a request? Or maybe fork this project and code the intended behaviour so I could download that? Then I could see if something from the autowire side could support that...

**Comment by marcgrue** [comment]
Hey, maybe the following approach could be adapted to work as a solution?:
https://geirsson.com/autowire-acl.html
